-- ============================================================
-- Hotel Seed Data - generated from וויגו-1.xlsx
-- 2026-05-29T09:57:20.028Z
-- ============================================================

BEGIN;

-- Networks
INSERT INTO hotel_networks (id, name, created_at, updated_at) VALUES ('ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'אטלס', NOW(), NOW()) ON CONFLICT (name) DO NOTHING;
INSERT INTO hotel_networks (id, name, created_at, updated_at) VALUES ('5e484ca6-4ecc-4332-be11-0bd1db93b886', 'מדנס', NOW(), NOW()) ON CONFLICT (name) DO NOTHING;
INSERT INTO hotel_networks (id, name, created_at, updated_at) VALUES ('7569dba9-5eb4-492f-a521-18dbb959ca6b', 'LOGIN', NOW(), NOW()) ON CONFLICT (name) DO NOTHING;
INSERT INTO hotel_networks (id, name, created_at, updated_at) VALUES ('63db9c11-b2ae-487f-94ec-aefa4f33a5dd', 'עצמאי', NOW(), NOW()) ON CONFLICT (name) DO NOTHING;

-- Hotels (viggo_registration_code and technician_code are excluded)
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('27a18cfb-d61f-4f0d-80f8-f7cedcf8dc11', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'ארתור', 'ירושלים', 'HOT', 'B-ZONE', 'SMTV', 'Wi-Fi', 'ענן', 'B-ZONE', 'סבה', NULL, NULL, 60, 60, NULL, 58, 'IPTV from HOT-VIGGO-WiFi', false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('2e620e46-a4a8-4705-ba50-ead093f0c026', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'רוטשילד 65', 'תל אביב', 'HOT', 'B-ZONE', 'STB', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', NULL, NULL, 76, 76, NULL, 75, 'חיבור VIGGO דרך נגן MECOOL למסכי TOSHIBA דרך LAN', false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('129aa24c-3465-41ae-89e0-7bf8fab7f56e', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'ארטיסט', 'תל אביב', 'HOT', 'B-ZONE', 'STM', NULL, 'ענן', 'B-ZONE', 'סבה', 'בוצע', NULL, 66, 66, NULL, 55, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('6e317953-e80e-4773-90d9-21d18cf27c57', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'בקסטג''', 'תל אביב', 'HOT', 'B-ZONE', 'SMTV', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', NULL, NULL, 52, 52, NULL, 48, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('a04be260-9393-4c24-93c8-cf7e3e4c9605', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'סינימה', 'תל אביב', 'HOT', 'B-ZONE', 'STB', 'Wi-Fi', 'ענן', 'B-ZONE', 'סבה', NULL, NULL, 89, 89, NULL, 85, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('86f5b36d-f48f-4258-bb1c-b987a96b2538', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'פאבריק', 'תל אביב', 'HOT', 'B-ZONE', 'STB', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', 'יש 3 טלוויזיות אנדרואיד', NULL, 47, 47, NULL, 43, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('34ad54f0-50ae-4b88-9b36-7ac33ab730e6', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'מרקט האוס', 'יפו', 'HOT', 'B-ZONE', 'STB', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', NULL, NULL, 45, 45, NULL, 44, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('1c3dba73-4653-424e-937e-f6737ffec5df', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'מלודי', 'תל אביב', 'HOT', 'B-ZONE', 'smtv/stb', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', 'הרוב - STB', NULL, 51, 51, NULL, 49, 'חיבור VIGGO דרך נגן MECOOL למסכי TOSHIBA דרך LAN', false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('19fbc3fc-50da-4bb2-bda8-01c7ce9577e5', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'שלום', 'תל אביב', 'HOT', 'B-ZONE', 'STB', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', NULL, NULL, 52, 52, NULL, 51, 'חיבור VIGGO דרך נגן MECOOL למסכי TOSHIBA דרך LAN', false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('f214a9e5-3d13-4ada-9632-4b357976dfea', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'טל', 'תל אביב', 'HOT', 'B-ZONE', 'STB', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', 'הרוב - STB, יש גם כמה SMTV', NULL, 124, 124, NULL, 123, 'חיבור VIGGO דרך נגן MECOOL למסכי TOSHIBA דרך LAN', false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('6287aa3a-46e4-4491-85e2-e2ea8e279b6d', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'ים', 'תל אביב', 'HOT', 'B-ZONE', 'STB', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', NULL, NULL, 42, 42, NULL, 42, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('dcdf3662-89d1-4b1d-8b13-beb8e890725b', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'בצלאל', 'ירושלים', 'HOT', 'B-ZONE', 'STB', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', 'עוד לא בוצע - ראו בתו "מדיהגייט"', NULL, NULL, NULL, 'יצאה הזמנה ל- 38', 37, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('74bc7f08-8927-4cac-b4a6-e7f65fac0393', 'ff59a58f-8f5b-42a8-b52a-cff97e6c6ec7', 'שדות', 'בי"ח אסף הרופא', 'HOT', 'B-ZONE', 'stb/smtv', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', 'עוד לא בוצע - ראו בתו "מדיהגייט"', NULL, NULL, NULL, 'סביב 55 חדרים', 55, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('41677be0-63b0-48a9-8141-444ef4596342', '5e484ca6-4ecc-4332-be11-0bd1db93b886', 'רוק130', 'תלאביב', 'HOT', 'B-ZONE', 'STB', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', 'עם TV אחד Wi-Fi', NULL, 29, 29, NULL, NULL, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('8a400d2e-7a77-49b7-92ed-749d62be7dd9', '5e484ca6-4ecc-4332-be11-0bd1db93b886', 'דירות בן-יהודה', 'תל-אביב', 'HOT', 'B-ZONE', 'stb/smtv', 'Ethernet', 'ענן', 'B-ZONE', 'סבה', NULL, NULL, 86, 86, NULL, NULL, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('6eda9ee8-491d-4fc5-8af2-13f8e882bdf3', '7569dba9-5eb4-492f-a521-18dbb959ca6b', 'לוגאין - 6', 'תל אביב', 'HOT', 'B-ZONE', 'STB', 'Wi-Fi', 'ענן', 'B-ZONE', 'מורג', NULL, NULL, 40, 40, NULL, NULL, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('fe99547d-3a5b-499a-bc28-63ba289dce96', '7569dba9-5eb4-492f-a521-18dbb959ca6b', 'לוגאין - 5', 'תל אביב', 'HOT', 'B-ZONE', 'SMTV', 'Ethernet', 'ענן', 'B-ZONE', 'מורג', NULL, NULL, 70, 70, NULL, NULL, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('fe9147e1-303b-4492-a6c7-90eb88b10cc4', '63db9c11-b2ae-487f-94ec-aefa4f33a5dd', 'הרצל דמוס', 'באר שבע', 'HOT', 'B-ZONE', 'SMTV', NULL, 'ענן', 'B-ZONE', 'חנן', 'אין להעביר קודים אלו לאדם שאינו מאושר', NULL, 18, 18, NULL, NULL, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('0bbc0c0d-c193-4714-9583-6cde89decd06', '63db9c11-b2ae-487f-94ec-aefa4f33a5dd', 'מלון מיכאל', 'חיפה', 'HOT', 'B-ZONE', 'SMTV', 'WiFi/Etarnt', 'ענן', 'B-ZONE', 'מורג', NULL, NULL, 21, 21, NULL, NULL, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('f103fc97-b19f-4e6c-aaca-93840f52e097', '63db9c11-b2ae-487f-94ec-aefa4f33a5dd', 'דריסקו', 'יפו', 'HOT', 'B-ZONE', 'STB', 'Etarnet', 'ענן', 'B-ZONE', 'סבה', NULL, NULL, 51, 51, NULL, NULL, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('092eae5a-be4b-4e62-a6d0-da9acc740bf3', '63db9c11-b2ae-487f-94ec-aefa4f33a5dd', 'לילי&בלום', 'תל-אביב', 'HOT', 'B-ZONE', 'SMTV', 'Etarnet', 'ענן', 'B-ZONE', 'סבה', 'ממתינים לטלוויזיות נוספות לסיום ההתקנה', NULL, 37, 37, NULL, NULL, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('0c9f2636-65d4-4407-88a6-936a215cb033', '63db9c11-b2ae-487f-94ec-aefa4f33a5dd', 'יד חרוצים', 'תל-אביב', 'HOT', 'B-ZONE', 'stb/smtv', 'Etarnet', 'ענן', 'B-ZONE', 'סבה', 'הוזמנו 13 טלויזיות נוספות לאתר', NULL, 49, 49, NULL, NULL, NULL, false, NOW(), NOW());
INSERT INTO hotels (id, network_id, name, location, content_provider, service_support, device_type, ip_connection, channel_source, switches, sales_person, notes, site_contact, active_spare_licenses, hot_license_count, hot_license_notes, room_count, remarks, is_deleted, created_at, updated_at) VALUES ('d0683fbd-bcda-41d3-bdc5-2644d3a2e0e7', '63db9c11-b2ae-487f-94ec-aefa4f33a5dd', 'סורוקה', 'בי"ח באר שבע', NULL, NULL, 'אין מידע', 'אין מידע', 'אין מידע', 'אין מידע', '?', 'לא הותקן על ידינו - אין מידע על האתר.', NULL, NULL, NULL, NULL, NULL, NULL, false, NOW(), NOW());

COMMIT;